services:
  distdur:
    image: dubhar/distanceduration:latest
    ports:
      - "80:80"
    volumes:
      - ./data:/var/www/html/data
    environment:
      - API_KEY=123456789 # Replace with valid API Key from OpenRouteService
    restart: unless-stopped

